sdkversion: 3.3.4
name: Golf
version: 0.1
vendor: rhomobile
build: distribution
bbver: 4.6
applog: rholog.txt
iphone:
  provisionprofile: 00F1DAE3-AC9B-48EB-8A7F-8DD298C9CECF
  sdk: iphoneos5.1
  codesignidentity: "iPhone Distribution: David van Prooijen"
  entitlements: 
  configuration: Distribution
  emulator: 5.1
  emulatortarget: iphone
  BundleIdentifier: com.davikko.golf
  BundleURLScheme: golf
wp:
  productid: 
  uid: 3928127822
android:
  version: 2.1
extensions: ["locationmanager"]
