#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in accelerometer_wrap.c
extern void Init_Accelerometer(void);

// this method executed once on start of program
void Init_Accelerometer_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_Accelerometer();

	// You can add some code to this place:


}

#ifdef __cplusplus
} //extern "C"
#endif