#!/bin/sh


if [ "$RHO_PLATFORM" = "android" ]; then

cd locationmanager/platform/android
rake --trace

elif [ "$RHO_PLATFORM" = "iphone" ]; then

cd locationmanager/platform/iphone
rake --trace

fi



